requestBody:
  required: true
  content:
    application/json:
      schema:
        properties:
          data:
            items:
              properties:
{% for feat in feature_openapi_named_tuple %}
                {{ feat.name }}:
                    format: {{ feat.format }}
                    nullable: False
                    type: {{ feat.type }}
                    required: true
    {% if feat.enum %}
                    enum: {{ feat.enum }}
    {% endif %}
{% endfor %}
            type: array
        required:
          - data
        type: object

responses:
  200:
    description: List of predictions
    content:
      application/json:
        schema:
          items:
            properties:
{% for target in target_openapi_named_tuple %}
              {{ target.name }}:
                format: {{ target.format }}
                nullable: False
                type: {{ target.type }}
                required: true
    {% if target.enum %}
                enum: {{ target.enum }}
    {% endif %}
{% endfor %}
          type: array
tags:
- predict