parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    $ref: '#/definitions/prediction_input'

responses:
  200:
    description: List of predictions
    schema:
      $ref: '#/definitions/predictions'

tags:
  - predict
definitions:
  prediction_input:
    properties:
      data:
        items:
          properties:
{% for feat in feature_openapi_named_tuple %}
            {{ feat.name }}:
              format: {{ feat.format }}
              type: {{ feat.type }}
  {% if feat.enum is not none %}
              enum: {{ feat.enum }}
  {% endif %}
  {% if feat.min_ is not none %}
              minimum: {{ feat.min_ }}
  {% endif %}
  {% if feat.max_ is not none %}
              maximum: {{ feat.max_ }}
    {% endif %}
{% endfor %}
        type: array
    required:
      - data
    type: object

  predictions:
    items:
      properties:
{% for target in target_openapi_named_tuple %}
        {{ target.name }}:
          format: {{ target.format }}
          type: {{ target.type }}
  {% if target.enum is not none %}
          enum: {{ target.enum }}
  {% endif %}
  {% if target.min_ is not none %}
          minimum: {{ target.min_ }}
  {% endif %}
  {% if target.max_ is not none%}
          maximum: {{ target.max_ }}
  {% endif %}
{% endfor %}
    type: array