requestBody:
  required: true
  content:
    application/json:
      schema:
        properties:
          data:
            items:
              properties:
{% for column in input_openapi_named_tuple %}
                {{ column.name }}:
                  format: {{ column.format }}
                  type: {{ column.type }}
  {% if column.enum is not none %}
                  enum: {{ column.enum }}
  {% endif %}
  {% if column.min_ is not none %}
                  minimum: {{ column.min_ }}
  {% endif %}
  {% if column.max_ is not none %}
                  maximum: {{ column.max_ }}
    {% endif %}
{% endfor %}
            type: array
        required:
          - data
        type: object

responses:
  200:
    description: List of predictions
    content:
      application/json:
        schema:
          items:
            properties:
{% for column in output_openapi_named_tuple %}
              {{ column.name }}:
                format: {{ column.format }}
                type: {{ column.type }}
  {% if column.enum is not none %}
                enum: {{ column.enum }}
  {% endif %}
  {% if column.min_ is not none %}
                minimum: {{ column.min_ }}
  {% endif %}
  {% if column.max_ is not none %}
                maximum: {{ column.max_ }}
  {% endif %}
{% endfor %}
          type: array
tags:
- Model_method_endpoints