parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    $ref: '#/definitions/{{ method_name }}_input'

responses:
  200:
    description: List of predictions
    schema:
      $ref: '#/definitions/{{ method_name }}_output'

tags:
  - Model_method_endpoints
definitions:
  {{ method_name }}_input:
    properties:
      data:
        items:
          required:
{% for column in input_openapi_named_tuple %}
          - {{ column.name }}
{% endfor %}
          properties:
{% for column in input_openapi_named_tuple %}
            {{ column.name }}:
              format: {{ column.format }}
              type: {{ column.type }}
  {% if column.enum is not none %}
              enum: {{ column.enum }}
  {% endif %}
  {% if column.min_ is not none %}
              minimum: {{ column.min_ }}
  {% endif %}
  {% if column.max_ is not none %}
              maximum: {{ column.max_ }}
  {% endif %}
{% endfor %}
        type: array
    required:
      - data
    type: object

  {{ method_name }}_output:
    items:
      properties:
{% for column in output_openapi_named_tuple %}
        {{ column.name }}:
          format: {{ column.format }}
          type: {{ column.type }}
  {% if column.enum is not none %}
          enum: {{ column.enum }}
  {% endif %}
  {% if column.min_ is not none %}
          minimum: {{ column.min_ }}
  {% endif %}
  {% if column.max_ is not none%}
          maximum: {{ column.max_ }}
  {% endif %}
{% endfor %}
    type: array